server:
  port: 8080
  origin: ${ORIGIN:*}
  servlet:
    context-path: /commands
spring:
  main:
    banner-mode: off
  output:
    ansi:
      enabled: ALWAYS
  application:
    name: commands
  rabbitmq:
    addresses: ${RABBITMQ_URI:amqp://guest:guest@localhost:5672}  
  data:
    mongodb:
        uri: ${MONGO_URI:mongodb://localhost:27017/account}
microservice:
  exchange: "core-demo"
  queue: "demo.commandhandles"
  storeName: "demo"
  routingKey: "org.example.#"

